#!/usr/bin/env python
from setup_utils import *
import os

# ids.r2dfoo

def uninstall():
    app = actions.getAppName("ids.r2dfoo")
    if app: actions.undeploy(app)

actions, arg, props = getActions("setup.properties", [])

prop_name = "run.properties"
prop_list = ["icat.url", "reader", 
"plugin.main.class", "plugin.main.dir", 
"plugin.archive.class", "maxRestoresPerThread", 
"plugin.zipMapper.class", 
"cache.dir", "preparedCount", "completedCount", "failedFilesCount", 
"sizeCheckIntervalSeconds", "startArchivingLevel1024bytes", "stopArchivingLevel1024bytes"]

if arg in ["CONFIGURE", "INSTALL"]: actions.configure(prop_name, prop_list)
idsProperties = getProperties(prop_name, prop_list)

if arg in ["CONFIGURE", "INSTALL"]:
    actions.checkNoErrors()

if arg == "INSTALL":

    if not os.path.exists(os.path.expandvars(idsProperties.get("cache.dir"))):
        abort("Please create directory " + idsProperties.get("cache.dir") + " as specified in run.properties")

    if idsProperties["plugin.archive.class"] == "org.icatproject.ids.storage.ArchiveSDStorageV2":
        if not idsProperties.get("plugin.archive.uri"):
            abort("plugin.archive.uri is not set in run.properties")
        if not idsProperties.get("plugin.archive.connectionTimeout"):
            abort("plugin.archive.connectionTimeout is not set in run.properties")
        if not idsProperties.get("plugin.archive.readTimeout"):
            abort("plugin.archive.readTimeout is not set in run.properties")

    try:
        uninstall()

        ovfiles = [[prop_name, "WEB-INF/classes"]]
        if os.path.exists("logback.xml"): ovfiles.append(["logback.xml", "WEB-INF/classes"])
        actions.deploy(deploymentorder=120, files=ovfiles)

    except Exception as e:
        raise
        abort(str(e))

if arg == "UNINSTALL":
    try:
       uninstall()
    except Exception as e:
        abort(str(e))
